version: "3.9"

services:
  app:
    container_name: "to-do"
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      sh -c "python3 manage.py migrate &&
             python3 manage.py runserver 0.0.0.0:8000"
    ports:
      - 8000:8000
    env_file:
      - ./.env
    volumes:
      # Used for hot reload
      - ./app:/app
    depends_on:
      - postgres
  to-do-postgres:
    container_name: "to-do-postgres"
    image: postgres:15.2-bullseye
    environment:
      - POSTGRES_DB=${POSTGRES_DB_NAME}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: